import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";

import "./globals.css";

import { Providers } from "@/components/providers";

const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    weight: ["400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${openSans.variable} ${montserrat.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
